---
title: "Bilancia a due piatti: rapporto di calibrazione"
short_title: "Rapporto di calibrazione"
logo: "unitn_logo.pdf"
logo_height: "1.2cm"
author: "Tommaso Raffaelli"
date: "`r Sys.Date()`"
company: "Dipartimento di Ingegneria Industriale, corso di Misure Industriali"
output: memor::pdf_memo
classoption: a4paper
number_sections: true
libertine: false
toc: true
lof: true
lot: false
header-includes: #\usepackage[italian]{babel}
---

```{r setup, echo=F, include=F}
# Caricamento librerie
library(knitr)
library(kableExtra)
library(tidyverse)
library(modelr)
library(purrr)

# Impostazioni output
knitr::opts_chunk$set(
	fig.align  = "center",      # allineamento figure
	fig.dim    = c(5, 3) * 1.2, # rapporto larghezza/altezza e fattore di scala
	out.height = "2.8in",       # altezza effettiva figure
	message    = FALSE,         # sopprimi messaggi
	warning    = FALSE,         # sopprimi warning
	echo       = TRUE,          # mostra i codice dei chunk
	include    = TRUE,          # mostra l'output dei chunk
	tidy       = TRUE,          # formatta il codice dei chunk
  tidy.opts  = list(width.cutoff=I(75)) # massima larghezza codice nei chunk
)
```
\newpage


# Preparazione dei dati

```{r}
Ord_dati <- expand.grid(
  Force_sx = seq(100, 500, 50),
  Delta_force = seq(-50, 50, 5),
  Result = NA
) %>% mutate(
  StdOrd = 1:n(),
  RunOrd = sample(n()),
  .before = Force_sx
) %>% arrange(RunOrd)
```

```{r tab1}
kable(Ord_dati[1:5, 1:5], booktabs = T, caption = "Tabella per l'ordine di test") %>%
  kable_styling(latex_options = c("striped", "HOLD_position"), position = "left")
```



